; RCT3 UI Scale Mod Configuration
; Place this file next to RCT3.exe or RCT3plus.exe alongside the proxy d3d9.dll.

[Master]

Enabled=1
; is the mod enabled?

[Features]

Scale=0
; =0 is auto scale based on resolution (1x @ 1080p -> 2x @ 4K),
; =1.5 is 1.5x scale, =2 is 2x scale, etc.

Borderless=1
; is borderless window used? Automatically matches your monitor's resolution.

[Debug]
; do not change values here unless advised!

Cache=1

Logging=0

Verbose=0
